### ISSUE TITLE
error with volatility on version 3.1

### ISSUE THREAD

**Issue by Objia** [memoryforensics1/Vol3xp#1]
└─$ vol -f attachment.raw volexp.Vol3xp                                                                                                1 ⨯
Volatility 3 Framework 2.0.0
Traceback (most recent call last):B scanning finished                      
  File "/usr/local/bin/vol", line 33, in <module>
    sys.exit(load_entry_point('volatility3==2.0.0', 'console_scripts', 'vol')())
  File "/usr/local/lib/python3.9/dist-packages/volatility3-2.0.0-py3.9.egg/volatility3/cli/__init__.py", line 625, in main
    CommandLine().run()
  File "/usr/local/lib/python3.9/dist-packages/volatility3-2.0.0-py3.9.egg/volatility3/cli/__init__.py", line 319, in run
    constructed = plugins.construct_plugin(ctx, automagics, plugin, base_config_path, progress_callback,
  File "/usr/local/lib/python3.9/dist-packages/volatility3-2.0.0-py3.9.egg/volatility3/framework/plugins/__init__.py", line 51, in construct_plugin
    constructed = plugin(context, plugin_config_path, progress_callback = progress_callback)
  File "/usr/local/lib/python3.9/dist-packages/volatility3-2.0.0-py3.9.egg/volatility3/plugins/volexp.py", line 10958, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/volatility3-2.0.0-py3.9.egg/volatility3/framework/interfaces/plugins.py", line 111, in __init__
    super().__init__(context, config_path)
  File "/usr/local/lib/python3.9/dist-packages/volatility3-2.0.0-py3.9.egg/volatility3/framework/interfaces/configuration.py", line 620, in __init__
    super().__init__()
  File "/usr/local/lib/python3.9/dist-packages/volatility3-2.0.0-py3.9.egg/volatility3/framework/interfaces/configuration.py", line 736, in __init__
    framework.require_interface_version(*self._required_framework_version)
  File "/usr/local/lib/python3.9/dist-packages/volatility3-2.0.0-py3.9.egg/volatility3/framework/__init__.py", line 48, in require_interface_version
    raise RuntimeError("Framework interface version {} is incompatible with required version {}".format(
RuntimeError: Framework interface version 2 is incompatible with required version 0

**Comment by memoryforensics1** [comment]
Fixed in the new version.
